name: Deploy runner

on:
  push:
    branches: ["main"]

jobs:
  build-job:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t news .

  test-job:
    name: Test
    needs: build-job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run container tests
        run: docker run --rm news
      - name: Run pytest
        run: pytest -s -v

  deploy-job:
    name: Deploy Application
    needs: test-job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with Docker Compose
        run: docker compose up -d