name: Deploy runner

on:
  push:
    branches: ["main"]

env:
  DOCKER_IMAGE: news

jobs:
  build-job:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

  test-job:
    name: Test
    needs: build-job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          docker run --rm pytest -s -v

  deploy-job:
    name: Deploy
    needs: test-job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          docker compose down
          docker compose up -d

      - name: Cleanup
        run: rm -f .env