name: Deploy runner

on:
  push:
    branches: ["main"]

env:
  DOCKER_IMAGE: news

jobs:
  build-job:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

  test-job:
    name: Test
    needs: build-job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          docker run --rm \
            $DOCKER_IMAGE \
            sh -c "pytest -s -v"

  deploy-job:
    name: Deploy
    needs: test-job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Stop and remove existing container
        run: |
          docker stop news || true
          docker rm news || true

      - name: Run new container
        run: |
          docker run -d \
            -p 1252:8000 \
            --env-file .env \
            --rm \
            --name news \
            $DOCKER_IMAGE

      - name: Cleanup
        run: rm -f .env